
export const ANNOTATION_MODE_PAGES = 'ANNOTATION_MODE_PAGES';
export const DISABLED_EXTENSION = 'DISABLED_EXTENSION';
export const DISABLED_PAGES = 'DISABLED_PAGES';

export const IAMSTAFF = 'IAMSTAFF';

export const REDUX_STORAGE = 'REDUX_STORAGE';
