
export const ANNOTATION_MODE_PAGES = 'ANNOTATION_MODE_PAGES';
export const DISABLED_EXTENSION = 'DISABLED_EXTENSION';
export const DISABLED_PAGES = 'DISABLED_PAGES';
export const ANNOTATION_REQUEST_FORM_DATA = 'ANNOTATION_REQUEST_FORM_DATA';

export const IAMSTAFF = 'IAMSTAFF';
