// login
export const EMULATE_ON_PP_AUTH_RESPONSE = 'EMULATE_ON_PP_AUTH_RESPONSE';

// simulate context menu click
export const EMULATE_ON_CONTEXT_MENU_ANNOTATE = 'EMULATE_ON_CONTEXT_MENU_ANNOTATE';
export const EMULATE_ON_CONTEXT_MENU_ANNOTATION_REQUEST = 'EMULATE_ON_CONTEXT_MENU_ANNOTATION_REQUEST';
